package MyForms;

import MyClasses.Functions;
import MyClasses.Member;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;


public class DeleteMemberForm extends javax.swing.JFrame {
    Functions func = new Functions();
    Member member = new MyClasses.Member();
    String imagePath = null;
    
    /**
     * Creates new form GenreForm
     */
    public DeleteMemberForm() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        func.displayImage(45, 45, null, "/MyImages/add_user.png", genreLabel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genrePanel = new javax.swing.JPanel();
        genreLabel = new javax.swing.JLabel();
        genreExit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Member_Id = new javax.swing.JTextField();
        jLabel_EmptyID = new javax.swing.JLabel();
        Add_Member = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        genrePanel.setBackground(new java.awt.Color(218, 186, 151));
        genrePanel.setBorder(BorderFactory.createMatteBorder(3,3,3,3, new Color(164,106,106)));

        genreLabel.setBackground(new java.awt.Color(164, 106, 106));
        genreLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        genreLabel.setForeground(new java.awt.Color(243, 236, 236));
        genreLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genreLabel.setText("  Delete Member");
        genreLabel.setOpaque(true);

        genreExit.setBackground(new java.awt.Color(164, 106, 106));
        genreExit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        genreExit.setForeground(new java.awt.Color(243, 236, 236));
        genreExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        genreExit.setText("X");
        genreExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        genreExit.setOpaque(true);
        genreExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                genreExitMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(6, 4, 6));
        jLabel4.setText("Enter ID:");

        Member_Id.setBackground(new java.awt.Color(243, 236, 236));
        Member_Id.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        Member_Id.setForeground(new java.awt.Color(6, 4, 6));
        Member_Id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Member_IdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Member_IdFocusLost(evt);
            }
        });
        Member_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Member_IdActionPerformed(evt);
            }
        });

        jLabel_EmptyID.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel_EmptyID.setForeground(new java.awt.Color(250, 0, 0));
        jLabel_EmptyID.setText("    ");
        jLabel_EmptyID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EmptyIDMouseClicked(evt);
            }
        });

        Add_Member.setBackground(new java.awt.Color(0, 117, 98));
        Add_Member.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Add_Member.setForeground(new java.awt.Color(243, 236, 236));
        Add_Member.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Add_Member.setText("Delete Member");
        Add_Member.setOpaque(true);
        Add_Member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_MemberMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Add_MemberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Add_MemberMouseExited(evt);
            }
        });

        javax.swing.GroupLayout genrePanelLayout = new javax.swing.GroupLayout(genrePanel);
        genrePanel.setLayout(genrePanelLayout);
        genrePanelLayout.setHorizontalGroup(
            genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genrePanelLayout.createSequentialGroup()
                .addGroup(genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(genreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Add_Member, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(genrePanelLayout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addGroup(genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(genrePanelLayout.createSequentialGroup()
                                    .addComponent(Member_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23))
                                .addComponent(jLabel_EmptyID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 0, 0)
                .addComponent(genreExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        genrePanelLayout.setVerticalGroup(
            genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genrePanelLayout.createSequentialGroup()
                .addGroup(genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreExit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(genrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Member_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addComponent(jLabel_EmptyID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Add_Member, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(genrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(genrePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Member_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Member_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Member_IdActionPerformed

    private void genreExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_genreExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_genreExitMouseClicked

    private void jLabel_EmptyIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EmptyIDMouseClicked
        // Hide this jlabel on click
        jLabel_EmptyID.setForeground(new Color(218,186,151));
    }//GEN-LAST:event_jLabel_EmptyIDMouseClicked

    private void Add_MemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_MemberMouseClicked
        // add a new member
        try {
            int id = Integer.parseInt(Member_Id.getText());
            
            int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this member?", "Delete Member", JOptionPane.YES_NO_OPTION);
            
            if (confirmation == JOptionPane.YES_OPTION){
                member.removeMember(id);
                
            // clear textfields
            Member_Id.setText("");
            
            // hide jLabel (empty messege)
            jLabel_EmptyID.setText("  ");
                
            }
        } catch (Exception e) {
            jLabel_EmptyID.setText("*Enter Member ID");
        }
    }//GEN-LAST:event_Add_MemberMouseClicked

    private void Add_MemberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_MemberMouseEntered
        Add_Member.setBackground(new Color(0, 92, 77));
    }//GEN-LAST:event_Add_MemberMouseEntered

    private void Add_MemberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_MemberMouseExited
        Add_Member.setBackground(new Color(0,117,98));
    }//GEN-LAST:event_Add_MemberMouseExited

    private void Member_IdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Member_IdFocusGained
        Member_Id.setBorder(new LineBorder(new Color(86,76,62), 2));
    }//GEN-LAST:event_Member_IdFocusGained

    private void Member_IdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Member_IdFocusLost
        Member_Id.setBorder(new LineBorder(new Color(218,186,151), 2));
    }//GEN-LAST:event_Member_IdFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Add_Member;
    private javax.swing.JTextField Member_Id;
    private javax.swing.JLabel genreExit;
    private javax.swing.JLabel genreLabel;
    private javax.swing.JPanel genrePanel;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_EmptyID;
    // End of variables declaration//GEN-END:variables
}
